/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FagfeltSlugRouteImport } from './routes/fagfelt/$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicWaitlistRouteImport } from './routes/api/public/waitlist'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicWaitlistVerifyRouteImport } from './routes/api/public/waitlist/verify'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FagfeltSlugRoute = FagfeltSlugRouteImport.update({
  id: '/fagfelt/$slug',
  path: '/fagfelt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaitlistRoute = ApiPublicWaitlistRouteImport.update({
  id: '/api/public/waitlist',
  path: '/api/public/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWaitlistVerifyRoute = ApiPublicWaitlistVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ApiPublicWaitlistRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/fagfelt/$slug': typeof FagfeltSlugRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/waitlist/verify': typeof ApiPublicWaitlistVerifyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/fagfelt/$slug': typeof FagfeltSlugRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/waitlist/verify': typeof ApiPublicWaitlistVerifyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/fagfelt/$slug': typeof FagfeltSlugRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/waitlist/verify': typeof ApiPublicWaitlistVerifyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/email/unsubscribe'
    | '/fagfelt/$slug'
    | '/api/public/waitlist'
    | '/lovable/email/suppression'
    | '/api/public/waitlist/verify'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/email/unsubscribe'
    | '/fagfelt/$slug'
    | '/api/public/waitlist'
    | '/lovable/email/suppression'
    | '/api/public/waitlist/verify'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/email/unsubscribe'
    | '/fagfelt/$slug'
    | '/api/public/waitlist'
    | '/lovable/email/suppression'
    | '/api/public/waitlist/verify'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  FagfeltSlugRoute: typeof FagfeltSlugRoute
  ApiPublicWaitlistRoute: typeof ApiPublicWaitlistRouteWithChildren
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fagfelt/$slug': {
      id: '/fagfelt/$slug'
      path: '/fagfelt/$slug'
      fullPath: '/fagfelt/$slug'
      preLoaderRoute: typeof FagfeltSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waitlist': {
      id: '/api/public/waitlist'
      path: '/api/public/waitlist'
      fullPath: '/api/public/waitlist'
      preLoaderRoute: typeof ApiPublicWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waitlist/verify': {
      id: '/api/public/waitlist/verify'
      path: '/verify'
      fullPath: '/api/public/waitlist/verify'
      preLoaderRoute: typeof ApiPublicWaitlistVerifyRouteImport
      parentRoute: typeof ApiPublicWaitlistRoute
    }
  }
}

interface ApiPublicWaitlistRouteChildren {
  ApiPublicWaitlistVerifyRoute: typeof ApiPublicWaitlistVerifyRoute
}

const ApiPublicWaitlistRouteChildren: ApiPublicWaitlistRouteChildren = {
  ApiPublicWaitlistVerifyRoute: ApiPublicWaitlistVerifyRoute,
}

const ApiPublicWaitlistRouteWithChildren =
  ApiPublicWaitlistRoute._addFileChildren(ApiPublicWaitlistRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  FagfeltSlugRoute: FagfeltSlugRoute,
  ApiPublicWaitlistRoute: ApiPublicWaitlistRouteWithChildren,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
