/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettPassordRouteImport } from './routes/sett-passord'
import { Route as RegistrerRouteImport } from './routes/registrer'
import { Route as LoggInnRouteImport } from './routes/logg-inn'
import { Route as GlemtPassordRouteImport } from './routes/glemt-passord'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FagfeltSlugRouteImport } from './routes/fagfelt/$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as MinSideLayoutRouteRouteImport } from './routes/min-side/_layout/route'
import { Route as MinSideLayoutIndexRouteImport } from './routes/min-side/_layout/index'
import { Route as MinSideLayoutProfilRouteImport } from './routes/min-side/_layout/profil'
import { Route as MinSideLayoutEirRouteImport } from './routes/min-side/_layout/eir'
import { Route as MinSideLayoutAktiviteterRouteImport } from './routes/min-side/_layout/aktiviteter'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicWaitlistRouteImport } from './routes/api/public/waitlist'
import { Route as ApiMemberEirRouteImport } from './routes/api/member/eir'
import { Route as ApiAuthSendResetLinkRouteImport } from './routes/api/auth/send-reset-link'
import { Route as ApiAuthSendMagicLinkRouteImport } from './routes/api/auth/send-magic-link'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicWaitlistVerifyRouteImport } from './routes/api/public/waitlist/verify'

const SettPassordRoute = SettPassordRouteImport.update({
  id: '/sett-passord',
  path: '/sett-passord',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrerRoute = RegistrerRouteImport.update({
  id: '/registrer',
  path: '/registrer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggInnRoute = LoggInnRouteImport.update({
  id: '/logg-inn',
  path: '/logg-inn',
  getParentRoute: () => rootRouteImport,
} as any)
const GlemtPassordRoute = GlemtPassordRouteImport.update({
  id: '/glemt-passord',
  path: '/glemt-passord',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FagfeltSlugRoute = FagfeltSlugRouteImport.update({
  id: '/fagfelt/$slug',
  path: '/fagfelt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MinSideLayoutRouteRoute = MinSideLayoutRouteRouteImport.update({
  id: '/min-side/_layout',
  path: '/min-side',
  getParentRoute: () => rootRouteImport,
} as any)
const MinSideLayoutIndexRoute = MinSideLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MinSideLayoutRouteRoute,
} as any)
const MinSideLayoutProfilRoute = MinSideLayoutProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => MinSideLayoutRouteRoute,
} as any)
const MinSideLayoutEirRoute = MinSideLayoutEirRouteImport.update({
  id: '/eir',
  path: '/eir',
  getParentRoute: () => MinSideLayoutRouteRoute,
} as any)
const MinSideLayoutAktiviteterRoute =
  MinSideLayoutAktiviteterRouteImport.update({
    id: '/aktiviteter',
    path: '/aktiviteter',
    getParentRoute: () => MinSideLayoutRouteRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaitlistRoute = ApiPublicWaitlistRouteImport.update({
  id: '/api/public/waitlist',
  path: '/api/public/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemberEirRoute = ApiMemberEirRouteImport.update({
  id: '/api/member/eir',
  path: '/api/member/eir',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSendResetLinkRoute = ApiAuthSendResetLinkRouteImport.update({
  id: '/api/auth/send-reset-link',
  path: '/api/auth/send-reset-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSendMagicLinkRoute = ApiAuthSendMagicLinkRouteImport.update({
  id: '/api/auth/send-magic-link',
  path: '/api/auth/send-magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWaitlistVerifyRoute = ApiPublicWaitlistVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ApiPublicWaitlistRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/glemt-passord': typeof GlemtPassordRoute
  '/logg-inn': typeof LoggInnRoute
  '/registrer': typeof RegistrerRoute
  '/sett-passord': typeof SettPassordRoute
  '/min-side': typeof MinSideLayoutRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/fagfelt/$slug': typeof FagfeltSlugRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/send-magic-link': typeof ApiAuthSendMagicLinkRoute
  '/api/auth/send-reset-link': typeof ApiAuthSendResetLinkRoute
  '/api/member/eir': typeof ApiMemberEirRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/min-side/aktiviteter': typeof MinSideLayoutAktiviteterRoute
  '/min-side/eir': typeof MinSideLayoutEirRoute
  '/min-side/profil': typeof MinSideLayoutProfilRoute
  '/min-side/': typeof MinSideLayoutIndexRoute
  '/api/public/waitlist/verify': typeof ApiPublicWaitlistVerifyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/glemt-passord': typeof GlemtPassordRoute
  '/logg-inn': typeof LoggInnRoute
  '/registrer': typeof RegistrerRoute
  '/sett-passord': typeof SettPassordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/fagfelt/$slug': typeof FagfeltSlugRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/send-magic-link': typeof ApiAuthSendMagicLinkRoute
  '/api/auth/send-reset-link': typeof ApiAuthSendResetLinkRoute
  '/api/member/eir': typeof ApiMemberEirRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/min-side/aktiviteter': typeof MinSideLayoutAktiviteterRoute
  '/min-side/eir': typeof MinSideLayoutEirRoute
  '/min-side/profil': typeof MinSideLayoutProfilRoute
  '/min-side': typeof MinSideLayoutIndexRoute
  '/api/public/waitlist/verify': typeof ApiPublicWaitlistVerifyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/glemt-passord': typeof GlemtPassordRoute
  '/logg-inn': typeof LoggInnRoute
  '/registrer': typeof RegistrerRoute
  '/sett-passord': typeof SettPassordRoute
  '/min-side/_layout': typeof MinSideLayoutRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/fagfelt/$slug': typeof FagfeltSlugRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/send-magic-link': typeof ApiAuthSendMagicLinkRoute
  '/api/auth/send-reset-link': typeof ApiAuthSendResetLinkRoute
  '/api/member/eir': typeof ApiMemberEirRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/min-side/_layout/aktiviteter': typeof MinSideLayoutAktiviteterRoute
  '/min-side/_layout/eir': typeof MinSideLayoutEirRoute
  '/min-side/_layout/profil': typeof MinSideLayoutProfilRoute
  '/min-side/_layout/': typeof MinSideLayoutIndexRoute
  '/api/public/waitlist/verify': typeof ApiPublicWaitlistVerifyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/glemt-passord'
    | '/logg-inn'
    | '/registrer'
    | '/sett-passord'
    | '/min-side'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/fagfelt/$slug'
    | '/api/auth/register'
    | '/api/auth/send-magic-link'
    | '/api/auth/send-reset-link'
    | '/api/member/eir'
    | '/api/public/waitlist'
    | '/lovable/email/suppression'
    | '/min-side/aktiviteter'
    | '/min-side/eir'
    | '/min-side/profil'
    | '/min-side/'
    | '/api/public/waitlist/verify'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/glemt-passord'
    | '/logg-inn'
    | '/registrer'
    | '/sett-passord'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/fagfelt/$slug'
    | '/api/auth/register'
    | '/api/auth/send-magic-link'
    | '/api/auth/send-reset-link'
    | '/api/member/eir'
    | '/api/public/waitlist'
    | '/lovable/email/suppression'
    | '/min-side/aktiviteter'
    | '/min-side/eir'
    | '/min-side/profil'
    | '/min-side'
    | '/api/public/waitlist/verify'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/glemt-passord'
    | '/logg-inn'
    | '/registrer'
    | '/sett-passord'
    | '/min-side/_layout'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/fagfelt/$slug'
    | '/api/auth/register'
    | '/api/auth/send-magic-link'
    | '/api/auth/send-reset-link'
    | '/api/member/eir'
    | '/api/public/waitlist'
    | '/lovable/email/suppression'
    | '/min-side/_layout/aktiviteter'
    | '/min-side/_layout/eir'
    | '/min-side/_layout/profil'
    | '/min-side/_layout/'
    | '/api/public/waitlist/verify'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GlemtPassordRoute: typeof GlemtPassordRoute
  LoggInnRoute: typeof LoggInnRoute
  RegistrerRoute: typeof RegistrerRoute
  SettPassordRoute: typeof SettPassordRoute
  MinSideLayoutRouteRoute: typeof MinSideLayoutRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  FagfeltSlugRoute: typeof FagfeltSlugRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthSendMagicLinkRoute: typeof ApiAuthSendMagicLinkRoute
  ApiAuthSendResetLinkRoute: typeof ApiAuthSendResetLinkRoute
  ApiMemberEirRoute: typeof ApiMemberEirRoute
  ApiPublicWaitlistRoute: typeof ApiPublicWaitlistRouteWithChildren
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sett-passord': {
      id: '/sett-passord'
      path: '/sett-passord'
      fullPath: '/sett-passord'
      preLoaderRoute: typeof SettPassordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrer': {
      id: '/registrer'
      path: '/registrer'
      fullPath: '/registrer'
      preLoaderRoute: typeof RegistrerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logg-inn': {
      id: '/logg-inn'
      path: '/logg-inn'
      fullPath: '/logg-inn'
      preLoaderRoute: typeof LoggInnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glemt-passord': {
      id: '/glemt-passord'
      path: '/glemt-passord'
      fullPath: '/glemt-passord'
      preLoaderRoute: typeof GlemtPassordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fagfelt/$slug': {
      id: '/fagfelt/$slug'
      path: '/fagfelt/$slug'
      fullPath: '/fagfelt/$slug'
      preLoaderRoute: typeof FagfeltSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/min-side/_layout': {
      id: '/min-side/_layout'
      path: '/min-side'
      fullPath: '/min-side'
      preLoaderRoute: typeof MinSideLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/min-side/_layout/': {
      id: '/min-side/_layout/'
      path: '/'
      fullPath: '/min-side/'
      preLoaderRoute: typeof MinSideLayoutIndexRouteImport
      parentRoute: typeof MinSideLayoutRouteRoute
    }
    '/min-side/_layout/profil': {
      id: '/min-side/_layout/profil'
      path: '/profil'
      fullPath: '/min-side/profil'
      preLoaderRoute: typeof MinSideLayoutProfilRouteImport
      parentRoute: typeof MinSideLayoutRouteRoute
    }
    '/min-side/_layout/eir': {
      id: '/min-side/_layout/eir'
      path: '/eir'
      fullPath: '/min-side/eir'
      preLoaderRoute: typeof MinSideLayoutEirRouteImport
      parentRoute: typeof MinSideLayoutRouteRoute
    }
    '/min-side/_layout/aktiviteter': {
      id: '/min-side/_layout/aktiviteter'
      path: '/aktiviteter'
      fullPath: '/min-side/aktiviteter'
      preLoaderRoute: typeof MinSideLayoutAktiviteterRouteImport
      parentRoute: typeof MinSideLayoutRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waitlist': {
      id: '/api/public/waitlist'
      path: '/api/public/waitlist'
      fullPath: '/api/public/waitlist'
      preLoaderRoute: typeof ApiPublicWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/member/eir': {
      id: '/api/member/eir'
      path: '/api/member/eir'
      fullPath: '/api/member/eir'
      preLoaderRoute: typeof ApiMemberEirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/send-reset-link': {
      id: '/api/auth/send-reset-link'
      path: '/api/auth/send-reset-link'
      fullPath: '/api/auth/send-reset-link'
      preLoaderRoute: typeof ApiAuthSendResetLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/send-magic-link': {
      id: '/api/auth/send-magic-link'
      path: '/api/auth/send-magic-link'
      fullPath: '/api/auth/send-magic-link'
      preLoaderRoute: typeof ApiAuthSendMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waitlist/verify': {
      id: '/api/public/waitlist/verify'
      path: '/verify'
      fullPath: '/api/public/waitlist/verify'
      preLoaderRoute: typeof ApiPublicWaitlistVerifyRouteImport
      parentRoute: typeof ApiPublicWaitlistRoute
    }
  }
}

interface MinSideLayoutRouteRouteChildren {
  MinSideLayoutAktiviteterRoute: typeof MinSideLayoutAktiviteterRoute
  MinSideLayoutEirRoute: typeof MinSideLayoutEirRoute
  MinSideLayoutProfilRoute: typeof MinSideLayoutProfilRoute
  MinSideLayoutIndexRoute: typeof MinSideLayoutIndexRoute
}

const MinSideLayoutRouteRouteChildren: MinSideLayoutRouteRouteChildren = {
  MinSideLayoutAktiviteterRoute: MinSideLayoutAktiviteterRoute,
  MinSideLayoutEirRoute: MinSideLayoutEirRoute,
  MinSideLayoutProfilRoute: MinSideLayoutProfilRoute,
  MinSideLayoutIndexRoute: MinSideLayoutIndexRoute,
}

const MinSideLayoutRouteRouteWithChildren =
  MinSideLayoutRouteRoute._addFileChildren(MinSideLayoutRouteRouteChildren)

interface ApiPublicWaitlistRouteChildren {
  ApiPublicWaitlistVerifyRoute: typeof ApiPublicWaitlistVerifyRoute
}

const ApiPublicWaitlistRouteChildren: ApiPublicWaitlistRouteChildren = {
  ApiPublicWaitlistVerifyRoute: ApiPublicWaitlistVerifyRoute,
}

const ApiPublicWaitlistRouteWithChildren =
  ApiPublicWaitlistRoute._addFileChildren(ApiPublicWaitlistRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GlemtPassordRoute: GlemtPassordRoute,
  LoggInnRoute: LoggInnRoute,
  RegistrerRoute: RegistrerRoute,
  SettPassordRoute: SettPassordRoute,
  MinSideLayoutRouteRoute: MinSideLayoutRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  FagfeltSlugRoute: FagfeltSlugRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthSendMagicLinkRoute: ApiAuthSendMagicLinkRoute,
  ApiAuthSendResetLinkRoute: ApiAuthSendResetLinkRoute,
  ApiMemberEirRoute: ApiMemberEirRoute,
  ApiPublicWaitlistRoute: ApiPublicWaitlistRouteWithChildren,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
